---

- name: Set pot openldap image IP address
  set_fact:
    pot_ldap_ip_address: "{{ [hostvars[item]['jailnet_ip'] ~ '.' ~ hostvars[item]['openldap_octet']] | list | join(' ') }}"
  loop: "{{ groups['ldap'] }}"
  when: "item == inventory_hostname"

- name: Initialize empty list for ldap_consul_servers_list
  set_fact:
    ldap_consul_servers_list: []
  
- name: Add IP addresses of consul servers to ldap_consul_servers_list
  set_fact:
    ldap_consul_servers_list: "{{ ldap_consul_servers_list + [hostvars[item]['jailnet_ip'] ~ '.' ~ hostvars[item]['consul_octet']] }}"
  loop: "{{ groups['consulservers'] }}"
  
- name: Print ldap_consul_servers_list
  debug:
    var: ldap_consul_servers_list
  
- name: Get a string version of ldap_consul_servers_list
  set_fact:
    ldap_consul_servers_list_string: "{{ ldap_consul_servers_list | join(',') }}"
  run_once: true
  
- name: Print ldap_consul_servers_list_string
  debug:
    var: ldap_consul_servers_list_string

# Check for gossip key
- name: Checking for existing gossip.key
  become: yes
  become_user: root
  shell: "ls /usr/local/etc/consul.d/gossip.key"
  register: filecheck_gossip_key
  ignore_errors: true
  changed_when: false
  check_mode: no
  run_once: true
  delegate_to: "{{ groups['consulservers'][0] }}"

- name: Read in gossip.key
  become: yes
  become_user: root
  shell:
    cmd: |
      cat /usr/local/etc/consul.d/gossip.key
  register: checking_existing_gossip_key
  when: "filecheck_gossip_key.rc == 0"
  run_once: true
  delegate_to: "{{ groups['consulservers'][0] }}"
  
- name: Set facts for gossip.key if not defined
  set_fact:
    consul_gossip_key: "{{ checking_existing_gossip_key.stdout }}"
  when: "consul_gossip_key is undefined"

- name: Check if zroot/{{ my_data_dataset }}/jaildata/openldap exists
  become: yes
  become_user: root
  ansible.builtin.command: "zfs list -t filesystem zroot/{{ my_data_dataset }}/jaildata/openldap"
  register: check_ldapdata_exists
  failed_when: no
  changed_when: "check_ldapdata_exists.rc != 0"

- name: Create zroot/{{ my_data_dataset }}/jaildata/openldap
  become: yes
  become_user: root
  shell:
    cmd: |
      zfs create -o mountpoint=/mnt/{{ my_data_dataset }}/jaildata/openldap zroot/{{ my_data_dataset }}/jaildata/openldap
  when: check_ldapdata_exists.rc == 1

- name: Set facts for openldap mount in
  set_fact:
    pot_ldap_mount_in: "/mnt/{{ my_data_dataset }}/jaildata/openldap"

- name: Check if we have {{ pot_ldap_pot_name }} installed
  become: yes
  become_user: root
  ansible.builtin.command: "/usr/local/bin/pot show -p {{ pot_ldap_pot_name }}"
  register: pot_ldap_installed
  failed_when: no
  changed_when: "pot_ldap_installed.rc != 0"

- name: Print out debug messages for {{ pot_ldap_pot_name }}
  ansible.builtin.debug:
    msg: openldap base image check output is {{ pot_ldap_installed.rc }}

- name: download the openldap pot image
  become: yes
  become_user: root
  shell:
    cmd: |
      pot import -p "{{ pot_ldap_base }}" -t "{{ pot_ldap_version }}" -U "{{ pot_ldap_url }}"
  when: "pot_ldap_installed.rc == 1"

- name: Check if {{ pot_ldap_clone_name }} exists
  become: yes
  become_user: root
  ansible.builtin.command: "/usr/local/bin/pot show -p {{ pot_ldap_clone_name }}"
  register: pot_ldap_clone_installed
  failed_when: no
  changed_when: "pot_ldap_clone_installed.rc != 0"

- name: Print out debug messages for {{ pot_ldap_clone_name }}
  ansible.builtin.debug:
    msg: openldap-clone check output is {{ pot_ldap_clone_installed.rc }}

- name: Clone the openldap pot image to {{ pot_ldap_clone_name }}
  become: yes
  become_user: root
  shell:
    cmd: |
      pot clone \
        -P "{{ pot_ldap_pot_name }}" \
        -p "{{ pot_ldap_clone_name }}" \
        -N alias -i "{{ my_jail_vlan }}|{{ pot_ldap_ip_address }}"
  when: pot_ldap_clone_installed.rc == 1

- name: Mount in the openldap persistent storage
  become: yes
  become_user: root
  shell:
    cmd: |
      pot mount-in -p {{ pot_ldap_clone_name }} \
        -d {{ pot_ldap_mount_in }} \
        -m {{ pot_ldap_mount_dest }}
  when: pot_ldap_clone_installed.rc == 1

- name: Set the pot parameters for {{ pot_ldap_clone_name }}
  become: yes
  become_user: root
  shell:
    cmd: |
      pot set-env -p "{{ pot_ldap_clone_name }}" \
        -E NODENAME="{{ shortname }}_{{ pot_ldap_nodename }}_server" \
        -E DATACENTER="{{ my_datacenter }}" \
        -E GOSSIPKEY="{{ consul_gossip_key }}" \
        -E IP="{{ pot_ldap_ip_address }}" \
        -E DOMAIN="{{ pot_ldap_domain_name }}" \
        -E MYCREDS="{{ pot_ldap_password }}" \
        -E HOSTNAME="{{ pot_ldap_hostname }}" \
        -E CRONBACKUP="{{ pot_ldap_cron_dir }}" \
        -E SERVERID="{{ pot_ldap_server_id }}" \
        -E DEFAULTGROUPS="{{ pot_ldap_default_groups }}" \
        -E USERNAME="{{ pot_ldap_generic_user }}" \
        -E PASSWORD="{{ pot_ldap_generic_pass }}" \
        -E REMOTELOG="{{ hostvars[groups['monitoring'][0]].jailnet_ip }}.{{ hostvars[groups['monitoring'][0]].beast_octet }}" \
        -E CONSULSERVERS={{ ldap_consul_servers_list_string }}
  when: pot_ldap_clone_installed.rc == 1

- name: Set the pot attributes for {{ pot_ldap_clone_name }}
  become: yes
  become_user: root
  shell:
    cmd: |
      pot set-attr -p "{{ pot_ldap_clone_name }}" -A start-at-boot -V True
  when: pot_ldap_clone_installed.rc == 1

- name: Start the {{ pot_ldap_clone_name }} image
  become: yes
  become_user: root
  shell:
    cmd: |
      pot start "{{ pot_ldap_clone_name }}"
  when: pot_ldap_clone_installed.rc == 1

- name: Wait for 30 seconds for images to start
  wait_for:
    timeout: 30
  when: "pot_ldap_clone_installed.rc == 1"

- name: Check if running pot is seasoned
  stat:
    path: /opt/pot/jails/{{ pot_ldap_clone_name }}/m/usr/local/etc/pot-is-seasoned
  register: result
  failed_when: result.stat.exists == false
  changed_when: none